### ISSUE TITLE
imdb.py opacus import package error

### ISSUE THREAD

**Issue by YukeWang96** [pytorch/opacus#318] opened 2021-12-24 21:57 UTC
running `imdb.py` under `examples/` will trigger a import package error
```
  File "imdb.py", line 14, in <module>
    from datasets import load_dataset
ModuleNotFoundError: No module named 'datasets'
```

**Comment by karthikprasad** [comment] 2021-12-29 18:26
Hello! I'm not able to reproduce this issue. Can you confirm you have installed opacus with the dev dependencies as mentioned in https://github.com/pytorch/opacus/tree/main/examples? If yes, please share a colab as it will be useful to debug.

**Comment by karthikprasad** [comment] 2022-01-04 17:26
Closing this for now; please feel free to reopen if the issue persists.

**Closed by karthikprasad** 2022-01-04 17:26 UTC
