### ISSUE TITLE
'PRVAccountant' object has no attribute 'get_privacy_spent' in Opacus code. Any solution please

### ISSUE THREAD

**Issue by Hafizamariaiqbal** [pytorch/opacus#562] opened 2023-02-13 15:23 UTC
## To Reproduce
> :warning: **We cannot help you without you sharing reproducible code**. Do not ignore this part :)

1.
2.
3.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:

```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by lucacorbucci** [comment] 2023-02-14 09:22
Hi, I had the same problem.
I replaced "get_privacy_spent" with "get_epsilon". I found this reading the PRVAccountant code https://github.com/pytorch/opacus/blob/a0a31baacc98b5d43e514f034ab2ee65bade9d39/opacus/accountants/prv.py#L30

**Comment by alexandresablayrolles** [comment] 2023-02-14 10:45
Closing as a duplicate of #560

**Closed by alexandresablayrolles** 2023-02-14 10:45 UTC
