### ISSUE TITLE
'type' object is not subscriptable when executing `from opacus import PrivacyEngine`

### ISSUE THREAD

**Issue by anirban-nath** [pytorch/opacus#310] opened 2021-12-10 16:12 UTC
As stated above, even if all dependencies are in place, I get the error "type' object is not subscriptable, at the line `from opacus import PrivacyEngine`. Solution?

**Comment by karthikprasad** [comment] 2021-12-10 20:17
@anirban-nath, can you share a colab notebook with the above issue? We are not able to reproduce this: https://colab.research.google.com/drive/1s1f8adyOIrqBWUNotJU55iW9IW2LG9bi?usp=sharing

**Comment by anirban-nath** [comment] 2021-12-10 21:49
Okay, so from what I understand, the line works fine when executed in isolation, but if syft is installed after opacus, then it breaks some dependencies. So, for federated learning purposes, install syft first, then opacus. Works fine after that.

**Comment by karthikprasad** [comment] 2021-12-11 02:50
@anirban-nath, I updated the above colab to install syft after opacus, and it still works fine. I'll close the issue now since it is not reproducible. Please feel free to reopen with a colab if you are still facing the issue.

**Closed by karthikprasad** 2021-12-11 02:50 UTC
