### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by rpanai** [pytorch/opacus#55] opened 2020-09-08 18:47 UTC
I'm trying to build a conda-forge package out of this but when I try to build the recipe with `conda skeleton pypi opacus` I have the following error

```
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
$PYTHONPATH = /tmp/tmpm3lk0o9wconda_skeleton_opacus-0.9.0.tar.gz/opacus-0.9.0
```

**Comment by Darktex** [comment] 2020-09-10 00:17
First of all, THANK YOU for looking into this! :)

So, I went on a Google rabbit hole on this one and it looks like the issue is that we did not include all the relevant resources. This seems fixed via adding a MANIFEST.in file that contains the necessary includes: https://stackoverflow.com/questions/43748284/requirements-txt-file-for-my-package-missing-from-pypi-install-and-tarball

@ffuuugor can you add it and issue a new release this week?

**Comment by rpanai** [comment] 2020-09-10 00:52
Please let me know whenever the new release is out so I'll proceed.

P.S. I just edited the issue as it was basically a copy and paste on the one I made [here](https://github.com/facebookincubator/submitit/issues/16)

**Closed** 2020-09-14 02:02 UTC
Labels: bug

**Comment by karthikprasad** [comment] 2020-09-14 02:04
The patch has landed, will be creating a new release this week.

**Comment by rpanai** [comment] 2020-09-21 16:23
@karthikprasad Any idea when the new release will be available?

**Comment by karthikprasad** [comment] 2020-09-21 18:03
@rpanai, the new release is out. Apologies for the delay; we wanted to get a few more changes in to this.
