### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'module'

### ISSUE THREAD

**Issue by jeff19960430** [pytorch/opacus#337] opened 2022-01-30 07:11 UTC
![image](https://user-images.githubusercontent.com/42458424/151690379-67aec344-395c-406b-bb24-0d16ca4f0ae2.png)

**Comment by jeff19960430** [comment] 2022-01-31 12:12
I fully follow the textbook 

model = Net()
optimizer = SGD(model.parameters(), lr=0.05)
data_loader = torch.utils.data.DataLoader(dataset, batch_size=1024)

privacy_engine = PrivacyEngine()
model, optimizer, data_loader = privacy_engine.make_private(
module=model,
optimizer=optimizer,
data_loader=data_loader,
noise_multiplier=1.1,
max_grad_norm=1.0,
)

but it's error

**Comment by gcormode** [comment] 2022-01-31 12:28
Hi Jeff, 

Can you give a complete example, e.g., by sharing a colab notebook, so we can try to reproduce this?  What model exactly are you using?

cheers
Graham

**Comment by karthikprasad** [comment] 2022-01-31 19:21
Duplicate of #336

**Comment by ffuuugor** [comment] 2022-01-31 22:50
Hi @jeff19960430 

It'd would be indeed helpful if you could share the full notebook and the environment. From the first glance it looks like you have older version of opacus installed. Please double check that your opacus version is >=1.0.0. We've changed the API in 1.0.0 and the notebook you're following using the updated interface.

Please feel free to reopen the issue if this doesn't help

**Closed by ffuuugor** 2022-01-31 22:50 UTC
Labels: duplicate

**Comment by jeff19960430** [comment] 2022-02-01 02:14
thank you , I find the probolem is the verion of the opacus.but I have two question in the new API:
1 、 the q (ratio of sammple ) = batch_size/sample_size ?
2、  for every empoch, should I need to resample and assemble the data and reinvoke the PrivacyEngine() interface ？

**Comment by jeff19960430** [comment] 2022-02-01 02:14
thank you , I find the probolem is the verion of the opacus.but I have two question in the new API:
1 、 the q (ratio of sammple ) = batch_size/sample_size ?
2、  for every empoch, should I need to resample and assemble the data and reinvoke the PrivacyEngine() interface ？

**Comment by ffuuugor** [comment] 2022-02-01 11:59
1) That's correct, yes. In the new API you don't need to provide sample rate explicitly, instead we derive it from the DataLoader object you provide

2) No, you don't need to recreate PrivacyEngine for every epoch. Privacy budget is tracked across the entire length of training, which could involve multiple epochs. Additionally, if you're using `make_private` method, you don't need to worry about sampling: the data loader object returned from `make_private` already uses the appropriate mechanism

Also just a reminder: you can always ask opacus-related questions and ask for support on PyTorch forums: https://discuss.pytorch.org/c/opacus/29

**Comment by jeff19960430** [comment] 2022-02-02 01:29
thank you very much

**Comment by jeff19960430** [comment] 2022-02-02 01:33
You mean I just have all the training data  into the data loader ready and it will automatically sample in  each epoch
