### ISSUE TITLE
Per sample gradient is not initialized. Not updated in backward pass? Any Solution??Can anyone post a link to the Colab notebook that has the solution implemented?

### ISSUE THREAD

**Issue by Hafizamariaiqbal** [pytorch/opacus#560] opened 2023-02-13 14:06 UTC

**Comment by alexandresablayrolles** [comment] 2023-02-13 15:26
Can you provide a minimal reproducing code?

**Comment by Hafizamariaiqbal** [comment] 2023-02-13 15:35
> Can you provide a minimal reproducing code?

Yes, I am sharing the Colab file.It would also help if you could reproduce it in a colab and share it.[https://drive.google.com/file/d/1VQgIk-W0Kxyz3ipI4C7WitMEbPth-_dO/view?usp=sharing](url)

**Comment by alexandresablayrolles** [comment] 2023-02-13 15:43
Thanks. You have to replace this line:
```
eps, best_alpha = self.privacy_engine.accountant.get_privacy_spent(
            delta=self.delta
        )
```
With this:
```
eps = self.privacy_engine.accountant.get_epsilon(
            delta=self.delta
        )
```

**Comment by Hafizamariaiqbal** [comment] 2023-02-14 10:19
> Thanks. You have to replace this line:
> 
> ```
> eps, best_alpha = self.privacy_engine.accountant.get_privacy_spent(
>             delta=self.delta
>         )
> ```
> 
> With this:
> 
> ```
> eps = self.privacy_engine.accountant.get_epsilon(
>             delta=self.delta
>         )
> ```

Thank you so much for Help. Now code is working.

**Comment by Hafizamariaiqbal** [comment] 2023-02-14 10:23
> > Thanks. You have to replace this line:
> > ```
> > eps, best_alpha = self.privacy_engine.accountant.get_privacy_spent(
> >             delta=self.delta
> >         )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > With this:
> > ```
> > eps = self.privacy_engine.accountant.get_epsilon(
> >             delta=self.delta
> >         )
> > ```
> 
> Thank you so much for Help. Now code is working.

One more help require if you can please. I want to represent results into a graph form.

**Comment by alexandresablayrolles** [comment] 2023-02-14 10:45
Closing the issue as the problem is solved. For the graph, I think you should keep a list like this:
```
epsilons = []
for ...:
    eps = self.privacy_engine.accountant.get_epsilon(
            delta=self.delta
        )
    epsilons.append(eps)
```
And then plot using something like
```
plt.plot(epsilons)
```

**Closed by alexandresablayrolles** 2023-02-14 10:45 UTC
