### ISSUE TITLE
LSTM name classifier bugs

### ISSUE THREAD

**Issue by woodyx218** [pytorch/opacus#110] opened 2021-01-06 05:43 UTC
## 🐛 Bug

I ran the exact code in the tutorial for char_rnn name classifier in Colab and observe two bugs:

1. the epsilon printed on my end is significantly smaller than 11.74 on the website. Actually I got eps=3.7 when reaching 50% with DP
2. the "print_every" is a typo, it should be "print_interval"

I also found `AttributeError: 'Parameter' object has no attribute 'grad_sample'' when running the exact code from the text classifier tutorial, in Colab. This is similar to https://github.com/pytorch/opacus/issues/4 but I don't see why this happens in the Bert case.

## Please reproduce using our [template Colab](https://colab.research.google.com/drive/1pCyN3_gN3WyhyQt8--eBPN5zVf2XZxiN?usp=sharing) and post here the link

https://github.com/pytorch/opacus/blob/master/tutorials/building_lstm_name_classifier.ipynb

https://github.com/pytorch/opacus/blob/master/tutorials/building_text_classifier.ipynb

## To Reproduce
> :warning: **We cannot help you without you sharing reproducible code**. Do not ignore this part :)

1. please re-run your code
2.
3.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:

```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by Darktex** [comment] 2021-01-08 00:04
Alrighty, I found the problem for the text classifier example. The root of the issue is that the model comes out from HuggingFace in eval mode, and we won't get grad_samples if the model is not in train mode. So this can be fixed by doing `model.train()` before starting to train.

That being said, that tutorial could use some dusting off. I'm working on a new version of it :)

The name classifier is easier to fix :) Simply put, that tutorial was based on a very old example. You are much better off running the new version of said example here: https://github.com/pytorch/opacus/blob/master/examples/char-lstm-classification.py

We are working on remaking that tutorial too, so that we just migrate you to the shiny new code

**Comment by woodyx218** [comment] 2021-01-08 15:10
Thank you for your timely response. I can run the text classifier now! I am aware of the new name classifier but still would appreciate if you can confirm that the epsilon is 3.7 instead of 11.74 on the current tutorial. By the way, when you remake that tutorial, will the old example be kept somewhere in opacus, just for reference of paper writing?

**Comment by Darktex** [comment] 2021-01-08 20:02
Your new epsilon is correct, I think. Very likely, the reason for this boost is that we reimplemented LSTM from scratch, and the new implementation works better in addition to being faster: we found it has higher numerical accuracy. If you had gotten better epsilon for the same number of iterations there would be something wrong, but it seems entirely reasonable to me that you get to 50% accuracy faster than before, hence with better epsilon.

Regarding keeping old examples, we can't do that :( We can't guarantee backwards compatibility to old examples. If we break them, we update them and the old version is reachable on GitHub. For example, if you wanted to reach the old version of the char-lstm tutorial, you could grab it from an old release such as eg https://github.com/pytorch/opacus/blob/v0.9.0/examples/char-lstm-classification.py 

If you need to reference it for a paper, I think it's reasonable to say something like "This was built on top of the Char LSTM example in Opacus 0.9.0". Would that work?

(BTW especially if you are writing a paper you should really really move to the new example. It will literally give you 20+ extra points in accuracy *and* better epsilon!)

**Comment by woodyx218** [comment] 2021-01-08 22:01
Yeah that reference method would work for me and thanks for the recommendation to the new classifier. Definitely will try it.
However, the epsilon seems to be a real issue for both classifier examples. I understand that privacy is only dependent on batch size, number of iterations, noise level, etc. My result of eps=3.7 is running the exact code of name classifier (hence with the same number of iterations; settings are iteration 1000, batch size 256, noise 1, clipping norm 1.5, delta 8e-5, not sure about sample size). The other eps=6.4 is also running the exact code of text classifier (3 epochs, virtual batch size 32, noise 0.4, clipping norm 0.1, sample size seems to be 570k, delta 1e-8). These can be checked in seconds without running the experiment for accuracy. Could you please double check both epsilons?

**Comment by romovpa** [comment] 2022-01-19 22:14
@woodyx218 
I've checked the examples. They show approximately same results (accuracy cannot be exactly reproduced because the random seed is not fixed). The learning speed is the same as in the main branch. 

In `building_lstm_name_classifier.ipynb` I got:
```
Epoch 3. Accuracy: 0.477452 | Loss: 1.894381 | (ε = 3.55, δ = 8e-05)
Epoch 4. Accuracy: 0.473887 | Loss: 1.852769 | (ε = 3.87, δ = 8e-05)
Epoch 5. Accuracy: 0.551742 | Loss: 1.588205 | (ε = 4.16, δ = 8e-05)
```
which is not far from [the website](https://opacus.ai/tutorials/building_lstm_name_classifier):
```
	 Epoch 3. Accuracy: 0.459604 | Loss: 1.958717
	 Epoch 4. Accuracy: 0.491896 | Loss: 1.782331
	 Epoch 5. Accuracy: 0.540205 | Loss: 1.577036
----------------------------
Test Accuracy: 0.559490 (ε = 4.16, δ = 8e-05)
```

> settings are iteration 1000, batch size 256, noise 1, clipping norm 1.5, delta 8e-5, not sure about sample size).
> The other eps=6.4 is also running the exact code of text classifier (3 epochs, virtual batch size 32, noise 0.4, clipping norm 0.1, sample size seems to be 570k, delta 1/sample size).

In [the example](https://github.com/pytorch/opacus/blob/main/tutorials/building_lstm_name_classifier.ipynb), noise level is set to reach epsilon not higher than 12 by the end of the last epoch (total 50), the batch size is set to 800.

When you change batch size or noise levels (e.g. by setting it manually to 1), epsilon-vs-iteration curve will be affected accordingly and should not be the same as in the tutorial.

I don't see obvious problems with the accounting or the tutorial. Since this issue is very old, I'm closing it. 
Please, feel free to reopen the issue if you believe there is a problem and provide a code snippet or a colab demonstrating the issue.

**Closed by romovpa** 2022-01-19 22:14 UTC
Labels: bug
